// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: helloworld.proto
#ifndef GRPC_helloworld_2eproto__INCLUDED
#define GRPC_helloworld_2eproto__INCLUDED

#include "helloworld.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace helloworld {

class Greeter GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::helloworld::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    virtual ::grpc::Status Fetch(::grpc::ClientContext* context, const ::helloworld::FetchRequest& request, ::helloworld::FetchReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::FetchReply>> AsyncFetch(::grpc::ClientContext* context, const ::helloworld::FetchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::FetchReply>>(AsyncFetchRaw(context, request, cq));
    }
    virtual ::grpc::Status Store(::grpc::ClientContext* context, const ::helloworld::StoreRequest& request, ::helloworld::StoreReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::StoreReply>> AsyncStore(::grpc::ClientContext* context, const ::helloworld::StoreRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::StoreReply>>(AsyncStoreRaw(context, request, cq));
    }
    virtual ::grpc::Status GetFileStat(::grpc::ClientContext* context, const ::helloworld::StatRequest& request, ::helloworld::StatReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::StatReply>> AsyncGetFileStat(::grpc::ClientContext* context, const ::helloworld::StatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::StatReply>>(AsyncGetFileStatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::helloworld::ListDirReply>> ListDir(::grpc::ClientContext* context, const ::helloworld::ListDirRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::helloworld::ListDirReply>>(ListDirRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helloworld::ListDirReply>> AsyncListDir(::grpc::ClientContext* context, const ::helloworld::ListDirRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::helloworld::ListDirReply>>(AsyncListDirRaw(context, request, cq, tag));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::FetchReply>* AsyncFetchRaw(::grpc::ClientContext* context, const ::helloworld::FetchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::StoreReply>* AsyncStoreRaw(::grpc::ClientContext* context, const ::helloworld::StoreRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::StatReply>* AsyncGetFileStatRaw(::grpc::ClientContext* context, const ::helloworld::StatRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::helloworld::ListDirReply>* ListDirRaw(::grpc::ClientContext* context, const ::helloworld::ListDirRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::helloworld::ListDirReply>* AsyncListDirRaw(::grpc::ClientContext* context, const ::helloworld::ListDirRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::helloworld::HelloReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    ::grpc::Status Fetch(::grpc::ClientContext* context, const ::helloworld::FetchRequest& request, ::helloworld::FetchReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::FetchReply>> AsyncFetch(::grpc::ClientContext* context, const ::helloworld::FetchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::FetchReply>>(AsyncFetchRaw(context, request, cq));
    }
    ::grpc::Status Store(::grpc::ClientContext* context, const ::helloworld::StoreRequest& request, ::helloworld::StoreReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::StoreReply>> AsyncStore(::grpc::ClientContext* context, const ::helloworld::StoreRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::StoreReply>>(AsyncStoreRaw(context, request, cq));
    }
    ::grpc::Status GetFileStat(::grpc::ClientContext* context, const ::helloworld::StatRequest& request, ::helloworld::StatReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::StatReply>> AsyncGetFileStat(::grpc::ClientContext* context, const ::helloworld::StatRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::StatReply>>(AsyncGetFileStatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::helloworld::ListDirReply>> ListDir(::grpc::ClientContext* context, const ::helloworld::ListDirRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::helloworld::ListDirReply>>(ListDirRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::helloworld::ListDirReply>> AsyncListDir(::grpc::ClientContext* context, const ::helloworld::ListDirRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::helloworld::ListDirReply>>(AsyncListDirRaw(context, request, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientAsyncResponseReader< ::helloworld::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::helloworld::HelloRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::helloworld::FetchReply>* AsyncFetchRaw(::grpc::ClientContext* context, const ::helloworld::FetchRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::helloworld::StoreReply>* AsyncStoreRaw(::grpc::ClientContext* context, const ::helloworld::StoreRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::helloworld::StatReply>* AsyncGetFileStatRaw(::grpc::ClientContext* context, const ::helloworld::StatRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientReader< ::helloworld::ListDirReply>* ListDirRaw(::grpc::ClientContext* context, const ::helloworld::ListDirRequest& request) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReader< ::helloworld::ListDirReply>* AsyncListDirRaw(::grpc::ClientContext* context, const ::helloworld::ListDirRequest& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_SayHello_;
    const ::grpc::RpcMethod rpcmethod_Fetch_;
    const ::grpc::RpcMethod rpcmethod_Store_;
    const ::grpc::RpcMethod rpcmethod_GetFileStat_;
    const ::grpc::RpcMethod rpcmethod_ListDir_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service() : service_(nullptr) {}
    virtual ~Service();
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::helloworld::HelloRequest* request, ::helloworld::HelloReply* response);
    virtual ::grpc::Status Fetch(::grpc::ServerContext* context, const ::helloworld::FetchRequest* request, ::helloworld::FetchReply* response);
    virtual ::grpc::Status Store(::grpc::ServerContext* context, const ::helloworld::StoreRequest* request, ::helloworld::StoreReply* response);
    virtual ::grpc::Status GetFileStat(::grpc::ServerContext* context, const ::helloworld::StatRequest* request, ::helloworld::StatReply* response);
    virtual ::grpc::Status ListDir(::grpc::ServerContext* context, const ::helloworld::ListDirRequest* request, ::grpc::ServerWriter< ::helloworld::ListDirReply>* writer);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    ::grpc::RpcService* service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestSayHello(::grpc::ServerContext* context, ::helloworld::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::helloworld::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestFetch(::grpc::ServerContext* context, ::helloworld::FetchRequest* request, ::grpc::ServerAsyncResponseWriter< ::helloworld::FetchReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestStore(::grpc::ServerContext* context, ::helloworld::StoreRequest* request, ::grpc::ServerAsyncResponseWriter< ::helloworld::StoreReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestGetFileStat(::grpc::ServerContext* context, ::helloworld::StatRequest* request, ::grpc::ServerAsyncResponseWriter< ::helloworld::StatReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestListDir(::grpc::ServerContext* context, ::helloworld::ListDirRequest* request, ::grpc::ServerAsyncWriter< ::helloworld::ListDirReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace helloworld


#endif  // GRPC_helloworld_2eproto__INCLUDED
